version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-network
    volumes:
      - zookeeper-data:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    volumes:
      - kafka-data:/bitnami/kafka

  cassandra:
    image: cassandra:3.11
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_CLUSTER_NAME=Learning Cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTENER_INTERFACE=eth0
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - kafka-network

  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - '9200:9200'
    networks:
      - kafka-network
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  zookeeper-data:
  kafka-data:
  cassandra-data:
  es-data:

networks:
  kafka-network:
    driver: bridge
