version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - zookeeper

  cassandra:
    image: cassandra:3.11
    ports:
      - '9042:9042' # Cổng mặc định để kết nối Cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=Learning Cluster
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_LISTENER_INTERFACE=eth0
    volumes:
      - cassandra-data:/var/lib/cassandra # Lưu dữ liệu Cassandra vào volume
    networks:
      - kafka-network

  elasticsearch:
    image: bitnami/elasticsearch:latest
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.security.enabled=false # Tắt bảo mật
      - xpack.security.http.ssl.enabled=false # Tắt SSL
    ports:
      - '9200:9200'
    networks:
      - kafka-network
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  cassandra-data: # Định nghĩa volume cho Cassandra
  es-data: # Định nghĩa volume cho Elasticsearch

networks:
  kafka-network:
    driver: bridge
