export enum ActionTypes {
  CREATE_USER = 'CREATE',
  UPDATE_USER = 'UPDATE',
  DELETE_USER = 'DELETE',
  FETCH_USER = 'FETCH',
  FETCH_USER_BY_ID = 'FETCH_BY_ID',
  FETCH_USER_BY_USERNAME = 'FETCH_BY_USERNAME',
}
